WIP : Improve vote
hugodelahousse/Yakosa-Node pull request #107
Opened 2019-10-07 09:16 UTC by nokiiam

close #106

2019-10-14 07:05 UTC, MrColorado requested changes

2019-10-14 07:05 UTC, MrColorado commented on src/graphql/apollo.ts
> +      const now = new Date();
T'es obligé de créer une constante rien que ça ?

2019-10-14 08:06 UTC, nokiiam commented on src/graphql/apollo.ts
> +      const now = new Date();
ouais nan je peux faire sans

2019-10-23 14:26 UTC, MrColorado submitted a review, later dismissed

2019-10-28 15:17 UTC, MrColorado approved these changes

2019-10-28 15:19 UTC, merged