WIP: Create parcours
hugodelahousse/Yakosa-Node pull request #87
Opened 2019-06-16 15:26 UTC by nokiiam

- [x] Algo de valeur de magasin basique
- [x] Test de l'algo
- [ ] Creation de la recursion principale
- [ ] test de la recursion
- [ ] amelioration de l'algo de valeur de magasin en prenant en compte le type de promotion
- [ ] test de cette amelioration
- [ ] ajout de la fonction de calcul de magasin en fonction des promotions deja choisis
- [ ] test de cette algo
- [ ] ajout du nouvelle algo dans la recursion principale
- [ ] nouveau test de la recursion
- [ ] optimisation de la recursion en utilisant la distance en vol d'oiseau
- [ ] optimisation de la recursion en reduisant le nombre de reevaluation
- [ ] verification de la longueur total avec une API externe
- [ ] ajout de reprise sur erreur quand le test final rate
- [ ] creation de la route graphql associes

2019-10-14 07:01 UTC, MrColorado requested changes

2019-10-14 07:01 UTC, MrColorado commented on src/entities/ListProduct.ts
> -  @RelationId((listProduct: ListProduct) => listProduct.product)
Pourquoi tu l'enlèves ?

2019-10-14 07:01 UTC, MrColorado commented on src/graphql/utils.ts
> +      distance: args.maxDistTravel ? String(args.maxDistTravel) : '1000',
Pas possible de définire `args.maxDistTravel` en tant que string de base ?

2019-10-14 07:01 UTC, MrColorado commented on src/tests/utils/CreateRandomObject.ts
> +    id: 1,
T'es sur que tu veux fix l'id à 1 ?

2019-10-14 07:01 UTC, MrColorado commented on src/tests/utils/CreateRandomObject.ts
> +    id: 1,
idem

2019-10-14 07:01 UTC, MrColorado commented on src/utils/CreateShoppingRoute.ts
> + * Function that must find the the stores tou must travel to
Pas très compréhensible ce commetaire

2019-10-14 07:01 UTC, MrColorado commented on src/utils/CreateShoppingRoute.ts
> +        if (res.value > maxValue) maxValue = res.value;
Un minimum de coding style

2019-10-14 07:01 UTC, MrColorado commented on src/utils/CreateShoppingRoute.ts
> +  if (promotion.unit != listProduct.unit) return 0;
idem coding style

2019-10-14 07:01 UTC, MrColorado commented on src/utils/CreateShoppingRoute.ts
> +    (listProduct.quantity / quantityOfNewPromo) * newPromo.price -
`quantityOfNewPromo` toujours diférent de 0 ?

2019-10-14 07:01 UTC, MrColorado commented on src/utils/CreateShoppingRoute.ts
> +    Math.trunc(listProduct.quantity / quantityOfNewPromo) * newPromo.promotion;
`quantityOfNewPromo` toujours différent de  0 ?

2019-10-14 07:01 UTC, MrColorado commented on src/utils/CreateShoppingRoute.ts
> +    Math.trunc(listProduct.quantity / quantityOfLastPromo) *
idem

2019-10-14 07:01 UTC, MrColorado commented on src/utils/CreateShoppingRoute.ts
> +    (listProduct.quantity / quantityOfLastPromo) * lastPromo.price -
idem

2019-10-14 07:01 UTC, MrColorado commented on src/utils/CreateShoppingRoute.ts
> +    let promoChosen: Promotion | null = null;
Je vois pas trop ce que tu veux faire ici

2019-10-14 07:01 UTC, MrColorado commented on src/utils/CreateShoppingRoute.ts
> +      promotionsChoice.push(promoChosen!);
Il sert à quoi le `!` ?

2019-10-14 07:10 UTC, nokiiam commented on src/entities/ListProduct.ts
> -  @RelationId((listProduct: ListProduct) => listProduct.product)
car les product n'ont pas d'id mais des barcode (il y a un relationID sur les barcode juste en dessous)

2019-10-14 07:11 UTC, nokiiam commented on src/graphql/utils.ts
> +      distance: args.maxDistTravel ? String(args.maxDistTravel) : '1000',
j'utilise aussi args.maxDistTravel comme nombre dans tous le reste de mon algorithme

2019-10-14 07:24 UTC, nokiiam commented on src/tests/utils/CreateRandomObject.ts
> +    id: 1,
c'est pas des fixtures, elles ont pas but à être utiliser pour mettre dans le sql mais pour tester l'algorithme de chemin. Mais je vais quand même remplacer l'Id par 0.

2019-10-14 07:24 UTC, nokiiam commented on src/tests/utils/CreateRandomObject.ts
> +    id: 1,
idem

2019-10-14 07:26 UTC, nokiiam commented on src/utils/CreateShoppingRoute.ts
> +    Math.trunc(listProduct.quantity / quantityOfNewPromo) * newPromo.promotion;
oui le type de quantityOfNewPromo c'est pas number c'est 1 | 2 | 3

2019-10-14 07:26 UTC, nokiiam commented on src/utils/CreateShoppingRoute.ts
> +    Math.trunc(listProduct.quantity / quantityOfLastPromo) *
idem

2019-10-14 07:27 UTC, nokiiam commented on src/utils/CreateShoppingRoute.ts
> +    (listProduct.quantity / quantityOfLastPromo) * lastPromo.price -
idem

2019-10-14 07:29 UTC, nokiiam commented on src/utils/CreateShoppingRoute.ts
> +    let promoChosen: Promotion | null = null;
l'instancier à une valeur par défaut. Mais c'est pas nécessairement utile en effet

2019-10-14 07:37 UTC, nokiiam commented on src/utils/CreateShoppingRoute.ts
> +    let promoChosen: Promotion | null = null;
ah si vu que je l'utilise dans un cas ou typescript arrive pas à déterminer si je l'ai déjà instancier il peut me crasher une erreur. Je prefère lui mettre une valeur par défault pour pas avoir le "use before being instanciated"

2019-10-14 07:37 UTC, nokiiam commented on src/utils/CreateShoppingRoute.ts
> +      promotionsChoice.push(promoChosen!);
garantir que dans ce cas la valeur ne vaut ni null ni undefined (vu que typescript ne sais pas que dans ce if promoChosen est toujours différent de null).

2019-10-14 07:42 UTC, nokiiam commented on src/utils/CreateShoppingRoute.ts
> +    (listProduct.quantity / quantityOfNewPromo) * newPromo.price -
oui le type de quantityOfNewPromo c'est pas number c'est 1 | 2 | 3

2019-10-14 07:58 UTC, nokiiam commented on src/utils/CreateShoppingRoute.ts
> +        if (res.value > maxValue) maxValue = res.value;
le linteur me demande de faire ça pour (je passe pas le lint sans)

2019-10-14 07:58 UTC, nokiiam commented on src/utils/CreateShoppingRoute.ts
> +  if (promotion.unit != listProduct.unit) return 0;
le linteur me demande de faire ça pour (je passe pas le lint sans)

2019-10-23 14:33 UTC, MrColorado submitted a review, later dismissed

2019-10-28 16:00 UTC, MrColorado approved these changes

2019-10-28 16:00 UTC, merged